name: Run Open_page_test.py

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

- name: Install selenium
  run: |
    pip install selenium
- name: Install other dependencies
  run: |
    pip install -r requirements.txt

    - name: Run Open_page_test.py
      run: python Open_page_test.py


    
